export enum IpcChannel {
  AppGetInfo = 'app:info:get',
  AppGetPaths = 'app:paths:get',
  AppShellOpenPath = 'app:shell:open-path',
  AppGetStorageStats = 'app:storage:stats',
  AppClearCache = 'app:storage:clear-cache',
  AppBackupData = 'app:storage:backup',
  AppRestoreData = 'app:storage:restore',
  AppResetData = 'app:storage:reset',
  AppDeleteKnowledge = 'app:storage:delete-knowledge',
  AppRuntimeSettingsSync = 'app:runtime-settings:sync',

  KnowledgeBaseList = 'knowledge:kb:list',
  KnowledgeBaseGet = 'knowledge:kb:get',
  KnowledgeBaseCreate = 'knowledge:kb:create',
  KnowledgeBaseUpdate = 'knowledge:kb:update',
  KnowledgeBaseDelete = 'knowledge:kb:delete',
  KnowledgeBaseStorageEnsure = 'knowledge:base:storage-ensure',

  KnowledgeDocumentList = 'knowledge:document:list',
  KnowledgeDocumentIngest = 'knowledge:document:ingest',
  KnowledgeDocumentDelete = 'knowledge:document:delete',
  KnowledgeDocumentReindex = 'knowledge:document:reindex',
  KnowledgeKbReindex = 'knowledge:kb:reindex',
  KnowledgeFtsRebuild = 'knowledge:fts:rebuild',
  KnowledgeSearch = 'knowledge:search',

  KnowledgeSourceList = 'knowledge:source:list',
  KnowledgeSourceAddFolder = 'knowledge:source:add-folder',
  KnowledgeSourceAddUrl = 'knowledge:source:add-url',
  KnowledgeSourceAddSitemap = 'knowledge:source:add-sitemap',
  KnowledgeSourceAddNotionExport = 'knowledge:source:add-notion-export',
  KnowledgeIngestJobList = 'knowledge:ingest-job:list',
  KnowledgeIngestJobCancel = 'knowledge:ingest-job:cancel',
  KnowledgeIngestJobRetry = 'knowledge:ingest-job:retry',
  KnowledgeFileRegistryList = 'knowledge:file-registry:list',

  MemoryEntryList = 'memory:entry:list',
  MemoryEntryDelete = 'memory:entry:delete',
  KnowledgeSourceRemove = 'knowledge:source:remove',
  KnowledgeWatchStatus = 'knowledge:watch:status',
  KnowledgeFolderEnsure = 'knowledge:folder:ensure',
  KnowledgeFolderGet = 'knowledge:folder:get',
  KnowledgeFolderScanPreview = 'knowledge:folder:scan-preview',
  KnowledgeFolderListFiles = 'knowledge:folder:list-files',
  KnowledgeFolderImportFiles = 'knowledge:folder:import-files',
  KnowledgeFolderDeleteFile = 'knowledge:folder:delete-file',
  KnowledgeNetworkFolderEnsure = 'knowledge:network-folder:ensure',
  KnowledgeNetworkFolderGet = 'knowledge:network-folder:get',
  KnowledgeLocalFilesFolderEnsure = 'knowledge:local-files-folder:ensure',
  KnowledgeLocalFilesFolderGet = 'knowledge:local-files-folder:get',
  KnowledgeDefaultFolderEnsureKb = 'knowledge:default-folder:ensure-kb',
  KnowledgeFileDedupScan = 'knowledge:file-dedup:scan',
  KnowledgeFileDedupScanCancel = 'knowledge:file-dedup:scan-cancel',
  KnowledgeFileDedupStream = 'knowledge:file-dedup:stream',
  KnowledgeFileDedupDelete = 'knowledge:file-dedup:delete',
  KnowledgeIngestStream = 'knowledge:ingest:stream',

  BlobUpload = 'blob:upload',
  BlobGetMeta = 'blob:get-meta',
  BlobGetDataUrl = 'blob:get-data-url',

  IdentityGet = 'identity:get',
  IdentityUpdate = 'identity:update',
  WorkspaceList = 'workspace:list',
  WorkspaceUpdate = 'workspace:update',
  WorkspaceGetDefault = 'workspace:get-default',
  WorkspaceGet = 'workspace:get',

  DialogSelectFolder = 'dialog:select-folder',
  DialogSelectFiles = 'dialog:select-files',
  DialogSelectFilesOrFolders = 'dialog:select-files-or-folders',
  DialogSaveFile = 'dialog:save-file',

  FileReadForChat = 'file:read-for-chat',
  ChatStageAttachments = 'file:chat-stage-attachments',

  NotesAttachmentImport = 'notes:attachment:import',
  NotesSyncExport = 'notes:sync:export',
  NotesDataSync = 'notes:data:sync',
  NotesDataLoad = 'notes:data:load',
  NotesGetById = 'notes:get-by-id',
  NotesIngestToKb = 'notes:ingest-to-kb',

  ProviderList = 'provider:list',
  ProviderCreate = 'provider:create',
  ProviderUpdate = 'provider:update',
  ProviderDelete = 'provider:delete',
  ProviderTest = 'provider:test',
  ProviderFetchModels = 'provider:fetch-models',

  AssistantList = 'assistant:list',
  AssistantCreate = 'assistant:create',
  AssistantUpdate = 'assistant:update',
  AssistantDelete = 'assistant:delete',
  AssistantDuplicate = 'assistant:duplicate',

  SessionCreate = 'agent:session:create',
  SessionList = 'agent:session:list',
  SessionGet = 'agent:session:get',
  SessionUpdate = 'agent:session:update',
  SessionDelete = 'agent:session:delete',
  SessionFork = 'agent:session:fork',
  SessionClearMessages = 'agent:session:clear-messages',

  MessageList = 'agent:message:list',
  MessageDelete = 'agent:message:delete',
  MessageSend = 'agent:message:send',
  MessageRegenerate = 'agent:message:regenerate',
  MessageTranslate = 'agent:message:translate',
  MessageDiagnose = 'agent:message:diagnose',
  MessageAbort = 'agent:message:abort',
  MessageAbortSession = 'agent:message:abort-session',
  MessageStream = 'agent:message:stream',
  AgentToolApprovalRequest = 'agent:tool-approval:request',
  AgentToolApprovalRespond = 'agent:tool-approval:respond',

  McpStatusList = 'mcp:status:list',
  McpServerList = 'mcp:server:list',
  McpServerUpsert = 'mcp:server:upsert',
  McpServerDelete = 'mcp:server:delete',
  McpServerTest = 'mcp:server:test',
  McpToolsList = 'mcp:tools:list',
  McpServerInspect = 'mcp:server:inspect',

  SkillList = 'skill:list',
  SkillInstall = 'skill:install',
  SkillDelete = 'skill:delete',

  ImChannelList = 'im-channel:list',
  ImChannelUpsert = 'im-channel:upsert',
  ImChannelTest = 'im-channel:test',
  ImChannelStatusList = 'im-channel:status:list',
  ImChannelWebhookInfo = 'im-channel:webhook:info',

  P2pPing = 'p2p:ping',

  P2pDeviceGetInfo = 'p2p:device:get-info',

  P2pDiscoveryStart = 'p2p:discovery:start',
  P2pDiscoveryStop = 'p2p:discovery:stop',
  P2pDiscoveryListNodes = 'p2p:discovery:list-nodes',

  P2pConnectionConnect = 'p2p:connection:connect',
  P2pConnectionDisconnect = 'p2p:connection:disconnect',
  P2pConnectionList = 'p2p:connection:list',

  P2pNetworkGetConfig = 'p2p:network:get-config',
  P2pNetworkSetStunServers = 'p2p:network:set-stun-servers',

  P2pWorkspaceCreate = 'p2p:workspace:create',
  P2pWorkspaceList = 'p2p:workspace:list',
  P2pWorkspaceGet = 'p2p:workspace:get',
  P2pWorkspaceUpdate = 'p2p:workspace:update',
  P2pWorkspaceDelete = 'p2p:workspace:delete',
  P2pWorkspaceLeave = 'p2p:workspace:leave',
  P2pWorkspaceGetStoragePath = 'p2p:workspace:get-storage-path',

  P2pMemberList = 'p2p:member:list',
  P2pMemberInvite = 'p2p:member:invite',
  P2pMemberJoin = 'p2p:member:join',
  P2pMemberRemove = 'p2p:member:remove',
  P2pMemberUpdateRole = 'p2p:member:update-role',
  P2pMemberTrustDevice = 'p2p:member:trust-device',

  P2pSyncStart = 'p2p:sync:start',
  P2pSyncStop = 'p2p:sync:stop',
  P2pSyncStatus = 'p2p:sync:status',
  P2pSyncForce = 'p2p:sync:force',

  P2pResourceUnshare = 'p2p:resource:unshare',
  P2pResourceList = 'p2p:resource:list',

  P2pFileUpload = 'p2p:file:upload',
  P2pFileDownload = 'p2p:file:download',
  P2pFileListVersions = 'p2p:file:list-versions',
  P2pFileList = 'p2p:file:list',

  P2pEventList = 'p2p:event:list',
  P2pEventGet = 'p2p:event:get',

  P2pAgentExportPackage = 'p2p:agent:export-package',
  P2pAgentImportPackage = 'p2p:agent:import-package',
  P2pAgentShare = 'p2p:agent:share',
  P2pAgentRemoveSessions = 'p2p:agent:remove-sessions',
  P2pAgentSetSessionPermission = 'p2p:agent:set-session-permission',
  P2pAgentOpenSession = 'p2p:agent:open-session',

  P2pGroupChatList = 'p2p:group-chat:list',
  P2pGroupChatSend = 'p2p:group-chat:send',
  P2pGroupChatDelete = 'p2p:group-chat:delete',

  P2pKnowledgeShare = 'p2p:knowledge:share',
  P2pKnowledgeSyncDocument = 'p2p:knowledge:sync-document',
  P2pKnowledgeRemoveDocuments = 'p2p:knowledge:remove-documents',

  P2pNoteShare = 'p2p:note:share',
  P2pNotePushUpdate = 'p2p:note:push-update',
  P2pNoteSetPermission = 'p2p:note:set-permission',
  P2pNoteListShareTargets = 'p2p:note:list-share-targets',

  CommunityHubHealth = 'community:hub:health',
  CommunityHubStatus = 'community:hub:status',

  CommunityUserMe = 'community:user:me',
  CommunityUserMeUpdate = 'community:user:me:update',

  CommunityResourceList = 'community:resource:list',
  CommunityResourceGet = 'community:resource:get',
  CommunityResourceCreate = 'community:resource:create',
  CommunityResourcePublish = 'community:resource:publish',
  CommunityResourcePatch = 'community:resource:patch',
  CommunityResourceDelete = 'community:resource:delete',
  CommunityResourceLike = 'community:resource:like',
  CommunityResourceDislike = 'community:resource:dislike',
  CommunityResourceFavorite = 'community:resource:favorite',

  CommunityInstall = 'community:install',
  CommunityInstallComplete = 'community:install:complete',
  CommunityInstallRollback = 'community:install:rollback',
  CommunityInstallHistory = 'community:install:history',

  CommunityReviewCreate = 'community:review:create',
  CommunityReviewList = 'community:review:list',
  CommunityReviewPatch = 'community:review:patch',
  CommunityReviewDelete = 'community:review:delete',

  CommunityNewsSourceList = 'community:news:sources:list',
  CommunityNewsSourceCreate = 'community:news:sources:create',
  CommunityNewsSourceDelete = 'community:news:sources:delete',
  CommunityNewsSourceFetch = 'community:news:fetch-sources',
  CommunityNewsList = 'community:news:list',
  CommunityNewsGet = 'community:news:get',
  CommunityNewsRecommended = 'community:news:recommended',
  CommunityNewsFavorite = 'community:news:favorite',
  CommunityNewsLike = 'community:news:like',
  CommunityNewsDislike = 'community:news:dislike',
  CommunityNewsCommentList = 'community:news:comments:list',
  CommunityNewsCommentCreate = 'community:news:comments:create',

  CommunityCommentList = 'community:comment:list',
  CommunityCommentCreate = 'community:comment:create',
  CommunityCommentDelete = 'community:comment:delete',
  CommunityCommentCount = 'community:comment:count',

  CommunityBoardMessageList = 'community:board:messages:list',
  CommunityBoardMessageCreate = 'community:board:messages:create',
  CommunityBoardMessageLike = 'community:board:message:like',
  CommunityBoardMessageDislike = 'community:board:message:dislike',
  CommunityBoardMessageFavorite = 'community:board:message:favorite',
  CommunityBoardMessageDelete = 'community:board:message:delete',

  CommunityTaskList = 'community:task:list',
  CommunityTaskGet = 'community:task:get',
  CommunityTaskCreate = 'community:task:create',
  CommunityTaskPatch = 'community:task:patch',
  CommunityTaskPublish = 'community:task:publish',
  CommunityTaskCancel = 'community:task:cancel',
  CommunityTaskApply = 'community:task:apply',
  CommunityTaskApplicationsList = 'community:task:applications:list',
  CommunityTaskApplicationAccept = 'community:task:application:accept',
  CommunityTaskDeliver = 'community:task:deliver',
  CommunityTaskAcceptDelivery = 'community:task:accept-delivery',
  CommunityTaskRejectDelivery = 'community:task:reject-delivery',
  CommunityTaskReviewCreate = 'community:task:review:create',
  CommunityTaskReviewList = 'community:task:review:list',

  CommunityOrderCreate = 'community:order:create',
  CommunityOrderGet = 'community:order:get',
  CommunityOrderUpdateStatus = 'community:order:status:update',

  CommunityModerationReport = 'community:moderation:report',
  CommunityModerationReportList = 'community:moderation:report:list',
  CommunityModerationReportResolve = 'community:moderation:report:resolve',
  CommunityModerationResourceSuspend = 'community:moderation:resource:suspend',
  CommunityModerationResourceApprove = 'community:moderation:resource:approve',
  CommunityModerationUserBan = 'community:moderation:user:ban',
  CommunityModerationLogsList = 'community:moderation:logs:list',
  CommunityModerationScan = 'community:moderation:scan',
  CommunityPresenceHeartbeat = 'community:presence:heartbeat',

  CommunityAdminList = 'community:admin:list',
  CommunityAdminSearch = 'community:admin:search',
  CommunityAdminAppoint = 'community:admin:appoint',
  CommunityAdminRevoke = 'community:admin:revoke',
}

/** P2P 推送事件（通过 window.api.subscribe 订阅，非 ipcMain.handle） */
export const P2P_PUSH_CHANNELS = [
  'p2p:discovery:node-online',
  'p2p:discovery:node-offline',
  'p2p:connection:state-change',
  'p2p:connection:error',
  'p2p:peer:trust-required',
  'p2p:sync:progress',
  'p2p:sync:completed',
  'p2p:sync:event-applied',
  'p2p:sync:error',
  'p2p:event:appended',
  'p2p:group-chat:message',
] as const

export type P2pPushChannel = (typeof P2P_PUSH_CHANNELS)[number]

export const SUBSCRIBE_CHANNELS = [
  IpcChannel.MessageStream,
  IpcChannel.KnowledgeIngestStream,
] as const

export type SubscribeChannel = (typeof SUBSCRIBE_CHANNELS)[number]
