import {
  EPC_COMMERCIAL_COMMAND_DESCRIPTION,
  EPC_COMMERCIAL_COMMAND_TEMPLATE,
  EPC_WORK1_BOQ_FORMAT_COMMAND_DESCRIPTION,
  EPC_WORK1_BOQ_FORMAT_COMMAND_TEMPLATE,
  EPC_WORK2_SHIPPING_CI_COMMAND_DESCRIPTION,
  EPC_WORK2_SHIPPING_CI_COMMAND_TEMPLATE,
  EPC_WORK5_PAYMENT_COMMAND_DESCRIPTION,
  EPC_WORK5_PAYMENT_COMMAND_TEMPLATE,
} from '@toolman/shared'

import type { SlashCommandItem } from '../chat/slash-commands'

export const EPC_SLASH_COMMANDS: SlashCommandItem[] = [
  {
    id: 'epc-work1-boq-format',
    command: EPC_WORK1_BOQ_FORMAT_COMMAND_TEMPLATE,
    description: EPC_WORK1_BOQ_FORMAT_COMMAND_DESCRIPTION,
    insert: EPC_WORK1_BOQ_FORMAT_COMMAND_TEMPLATE,
  },
  {
    id: 'epc-work2-shipping-ci',
    command: EPC_WORK2_SHIPPING_CI_COMMAND_TEMPLATE,
    description: EPC_WORK2_SHIPPING_CI_COMMAND_DESCRIPTION,
    insert: EPC_WORK2_SHIPPING_CI_COMMAND_TEMPLATE,
  },
  {
    id: 'epc-work4-ipc-boq',
    command: EPC_COMMERCIAL_COMMAND_TEMPLATE,
    description: EPC_COMMERCIAL_COMMAND_DESCRIPTION,
    insert: EPC_COMMERCIAL_COMMAND_TEMPLATE,
  },
  {
    id: 'epc-work5-payment',
    command: EPC_WORK5_PAYMENT_COMMAND_TEMPLATE,
    description: EPC_WORK5_PAYMENT_COMMAND_DESCRIPTION,
    insert: EPC_WORK5_PAYMENT_COMMAND_TEMPLATE,
  },
]
