export const OTP_CODE_TTL_MINUTES = 2
export const OTP_CODE_TTL_SECONDS = OTP_CODE_TTL_MINUTES * 60
export const OTP_CODE_TTL_MS = OTP_CODE_TTL_SECONDS * 1000
export const OTP_RESEND_COOLDOWN_SECONDS = 60
