/** AUTO-GENERATED by scripts/write-build-provenance.mjs — do not edit manually. */
export const TOOLMAN_BUILD_PROVENANCE = {
  "product": "Toolman",
  "version": "0.5.0-rc.7",
  "copyrightNotice": "Copyright (C) 2024–2026 Toolman Contributors",
  "license": "AGPL-3.0-or-later",
  "repository": "https://github.com/wangxy2020/Toolman",
  "gitCommit": "a7ad2cbe670292ff2794e78566843d8f8e48bd0c",
  "gitDirty": true,
  "builtAt": "2026-08-02T17:44:25.324Z",
  "buildId": "36638819649bb427",
  "buildFingerprint": "36638819649bb427ebb654da639f5d382881a176ffccb94001e4e9dda8787513"
} as const
