/** AUTO-GENERATED by scripts/write-build-provenance.mjs — do not edit manually. */
export const TOOLMAN_BUILD_PROVENANCE = {
  "product": "Toolman",
  "version": "0.7.0-rc.3.7",
  "copyrightNotice": "Copyright (C) 2024–2026 Toolman Contributors",
  "license": "AGPL-3.0-or-later",
  "repository": "https://github.com/wangxy2020/Toolman",
  "gitCommit": "7976dc29bde61ab0ddbd564da72e5064c0ff7c5f",
  "gitDirty": false,
  "builtAt": "2026-08-21T05:13:35.035Z",
  "buildId": "d0521f1d3d6df3c6",
  "buildFingerprint": "d0521f1d3d6df3c63551b46561f87ed118a20d1615e2b75ce91e1c04e4186548"
} as const
