/** AUTO-GENERATED by scripts/write-build-provenance.mjs — do not edit manually. */
export const TOOLMAN_BUILD_PROVENANCE = {
  "product": "Toolman",
  "version": "0.7.0-rc.2.3",
  "copyrightNotice": "Copyright (C) 2024–2026 Toolman Contributors",
  "license": "AGPL-3.0-or-later",
  "repository": "https://github.com/wangxy2020/Toolman",
  "gitCommit": "493f96a53f14d3d52747ea4b384484f85a436b79",
  "gitDirty": false,
  "builtAt": "2026-08-16T16:22:39.106Z",
  "buildId": "a478101fc2ebdc75",
  "buildFingerprint": "a478101fc2ebdc75fe6256e41bb2a8d170fdc13c6e2a70aaacd4a9bedf262d6e"
} as const
