import { TOOLMAN_SOURCE_REPOSITORY } from '@toolman/shared'

export const TOOLMAN_GITHUB_URL = TOOLMAN_SOURCE_REPOSITORY

const TOOLMAN_LICENSE_URL = `${TOOLMAN_GITHUB_URL}/blob/main/LICENSE`
export const TOOLMAN_THIRD_PARTY_NOTICES_URL = `${TOOLMAN_GITHUB_URL}/blob/main/THIRD_PARTY_NOTICES.md`

export const TOOLMAN_JOIN_US_QQ_GROUP = '1054710968'
export const TOOLMAN_JOIN_US_QQ = '31897124'

export const ABOUT_EXTERNAL_LINK_URLS = {
  docs: `${TOOLMAN_GITHUB_URL}#readme`,
  changelog: `${TOOLMAN_GITHUB_URL}/blob/main/docs/engineering/RELEASE_STATUS.md`,
  website: TOOLMAN_GITHUB_URL,
  license: TOOLMAN_LICENSE_URL,
  thirdParty: TOOLMAN_THIRD_PARTY_NOTICES_URL,
} as const
