import {
  EPC_COMMERCIAL_DEFAULT_QUICK_PHRASE_ID,
  EPC_COMMERCIAL_QUICK_PHRASE_CONTENT,
  EPC_COMMERCIAL_QUICK_PHRASE_CONTENT_REVISION,
  EPC_COMMERCIAL_QUICK_PHRASE_TITLE,
} from './epcCommercialQuickPhrase.js'
import {
  EPC_WORK1_BOQ_FORMAT_DEFAULT_QUICK_PHRASE_ID,
  EPC_WORK1_BOQ_FORMAT_QUICK_PHRASE_CONTENT,
  EPC_WORK1_BOQ_FORMAT_QUICK_PHRASE_CONTENT_REVISION,
  EPC_WORK1_BOQ_FORMAT_QUICK_PHRASE_TITLE,
} from './epcWork1BoqFormatQuickPhrase.js'
import {
  EPC_WORK2_SHIPPING_CI_DEFAULT_QUICK_PHRASE_ID,
  EPC_WORK2_SHIPPING_CI_QUICK_PHRASE_CONTENT,
  EPC_WORK2_SHIPPING_CI_QUICK_PHRASE_CONTENT_REVISION,
  EPC_WORK2_SHIPPING_CI_QUICK_PHRASE_TITLE,
} from './epcWork2ShippingCiQuickPhrase.js'
import {
  EPC_WORK5_PAYMENT_DEFAULT_QUICK_PHRASE_ID,
  EPC_WORK5_PAYMENT_QUICK_PHRASE_CONTENT,
  EPC_WORK5_PAYMENT_QUICK_PHRASE_CONTENT_REVISION,
  EPC_WORK5_PAYMENT_QUICK_PHRASE_TITLE,
} from './epcWork5PaymentQuickPhrase.js'

export type EpcBuiltinQuickPhrase = {
  id: string
  label: string
  text: string
  revision: number
}

export const EPC_BUILTIN_QUICK_PHRASES: EpcBuiltinQuickPhrase[] = [
  {
    id: EPC_WORK1_BOQ_FORMAT_DEFAULT_QUICK_PHRASE_ID,
    label: EPC_WORK1_BOQ_FORMAT_QUICK_PHRASE_TITLE,
    text: EPC_WORK1_BOQ_FORMAT_QUICK_PHRASE_CONTENT,
    revision: EPC_WORK1_BOQ_FORMAT_QUICK_PHRASE_CONTENT_REVISION,
  },
  {
    id: EPC_WORK2_SHIPPING_CI_DEFAULT_QUICK_PHRASE_ID,
    label: EPC_WORK2_SHIPPING_CI_QUICK_PHRASE_TITLE,
    text: EPC_WORK2_SHIPPING_CI_QUICK_PHRASE_CONTENT,
    revision: EPC_WORK2_SHIPPING_CI_QUICK_PHRASE_CONTENT_REVISION,
  },
  {
    id: EPC_COMMERCIAL_DEFAULT_QUICK_PHRASE_ID,
    label: EPC_COMMERCIAL_QUICK_PHRASE_TITLE,
    text: EPC_COMMERCIAL_QUICK_PHRASE_CONTENT,
    revision: EPC_COMMERCIAL_QUICK_PHRASE_CONTENT_REVISION,
  },
  {
    id: EPC_WORK5_PAYMENT_DEFAULT_QUICK_PHRASE_ID,
    label: EPC_WORK5_PAYMENT_QUICK_PHRASE_TITLE,
    text: EPC_WORK5_PAYMENT_QUICK_PHRASE_CONTENT,
    revision: EPC_WORK5_PAYMENT_QUICK_PHRASE_CONTENT_REVISION,
  },
]
