import { StyleSheet } from 'react-native'
import { colors } from '../theme'

export const styles = StyleSheet.create({
  card: {
    width: '100%',
    backgroundColor: colors.bg,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 2,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    paddingHorizontal: 18,
    paddingVertical: 16,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.borderLight,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
  },
  githubBtn: {
    width: 40,
    height: 40,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  githubBtnPressed: {
    backgroundColor: colors.hover,
  },
  hero: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    padding: 18,
  },
  logo: {
    width: 56,
    height: 56,
    borderRadius: 12,
  },
  heroText: {
    flex: 1,
    minWidth: 0,
  },
  name: {
    marginBottom: 4,
    fontSize: 18,
    fontWeight: '600',
    color: colors.text,
  },
  tagline: {
    marginBottom: 8,
    fontSize: 13,
    lineHeight: 18,
    color: colors.textSecondary,
  },
  versionBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
    backgroundColor: colors.accentSoft,
    color: colors.accent,
    fontSize: 12,
    fontWeight: '500',
    overflow: 'hidden',
  },
  copyright: {
    marginTop: 8,
    fontSize: 11,
    lineHeight: 15,
    color: colors.textSecondary,
  },
  updateHint: {
    marginTop: 0,
    marginHorizontal: 18,
    marginBottom: 8,
    fontSize: 12,
    lineHeight: 17,
    color: colors.textSecondary,
  },
  divider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: colors.borderLight,
    marginHorizontal: 18,
  },
  toggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  toggleLabel: {
    fontSize: 14,
    color: colors.text,
  },
  switchTrack: {
    width: 40,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#d7dbe0',
    padding: 2,
    justifyContent: 'center',
    opacity: 0.55,
  },
  switchThumb: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#fff',
  },
  autoUpdateHint: {
    paddingHorizontal: 18,
    paddingBottom: 14,
    fontSize: 12,
    lineHeight: 18,
    color: colors.textSecondary,
  },
  linksCard: {
    paddingVertical: 4,
  },
  linkRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  linkRowBorder: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.borderLight,
  },
  linkLabel: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
    minWidth: 0,
  },
  linkIcon: {
    width: 16,
    height: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  linkLabelText: {
    flexShrink: 1,
    fontSize: 14,
    color: colors.text,
  },
  outlineBtn: {
    flexShrink: 0,
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    backgroundColor: colors.bg,
  },
  outlineBtnSm: {
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  outlineBtnAccent: {
    borderColor: colors.accent,
    backgroundColor: colors.accent,
  },
  outlineBtnPressed: {
    backgroundColor: colors.hover,
  },
  outlineBtnAccentPressed: {
    backgroundColor: colors.accentHover,
    borderColor: colors.accentHover,
  },
  outlineBtnDisabled: {
    opacity: 0.55,
  },
  outlineBtnText: {
    fontSize: 13,
    color: colors.textSecondary,
  },
  outlineBtnTextSm: {
    fontSize: 12,
  },
  outlineBtnTextAccent: {
    color: '#ffffff',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.28)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  modalDialog: {
    width: '100%',
    maxWidth: 400,
    maxHeight: '90%',
    borderRadius: 12,
    backgroundColor: colors.bg,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    paddingHorizontal: 24,
    paddingVertical: 16,
  },
  modalTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.text,
  },
  modalClose: {
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalCloseText: {
    fontSize: 22,
    lineHeight: 24,
    color: colors.textSecondary,
  },
  modalBody: {
    paddingHorizontal: 24,
    paddingTop: 8,
    paddingBottom: 24,
    alignItems: 'center',
  },
  qrWrap: {
    marginBottom: 14,
    alignItems: 'center',
  },
  qrImage: {
    width: 240,
    height: 320,
    borderRadius: 12,
  },
  joinWelcome: {
    fontSize: 14,
    lineHeight: 24,
    color: colors.textSecondary,
    textAlign: 'center',
  },
})
