import { Platform, StyleSheet } from 'react-native'
import { colors } from '../theme'

export const chatComposerStyles = StyleSheet.create({
  area: {
    paddingTop: 8,
    paddingBottom: 30,
    backgroundColor: colors.bg,
  },
  box: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    backgroundColor: colors.surface,
    overflow: 'hidden',
    position: 'relative',
  },
  toolbar: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 2,
    paddingHorizontal: 10,
    paddingTop: 8,
    paddingBottom: 2,
    paddingRight: 28,
  },
  tool: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  toolActive: {
    backgroundColor: colors.accentSoft,
  },
  toolDisabled: {
    opacity: 0.35,
  },
  emojiPicker: {
    marginHorizontal: 8,
    marginBottom: 8,
    paddingVertical: 6,
    paddingHorizontal: 6,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    backgroundColor: colors.bg,
    overflow: 'hidden',
    shadowColor: '#0f172a',
    shadowOpacity: 0.12,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 6,
  },
  emojiScroll: {
    maxHeight: 168,
  },
  emojiGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 0,
  },
  emojiItem: {
    width: 28,
    height: 28,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emojiItemPressed: {
    backgroundColor: colors.hover,
  },
  emojiText: {
    fontSize: 18,
    lineHeight: 22,
  },
  slashMenu: {
    marginHorizontal: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    backgroundColor: colors.bg,
    overflow: 'hidden',
    shadowColor: '#0f172a',
    shadowOpacity: 0.12,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 6,
  },
  slashBody: {
    maxHeight: 320,
  },
  slashRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: 'transparent',
  },
  slashRowActive: {
    backgroundColor: colors.hover,
  },
  slashRowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexShrink: 0,
  },
  slashCommand: {
    fontSize: 13,
    lineHeight: 17,
    color: colors.text,
    fontFamily: Platform.select({
      ios: 'Menlo',
      android: 'monospace',
      default: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    }),
  },
  slashDesc: {
    flex: 1,
    minWidth: 0,
    fontSize: 12,
    lineHeight: 17,
    color: colors.textSecondary,
    textAlign: 'right',
  },
  slashFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
    backgroundColor: colors.hover,
  },
  slashFooterTitle: {
    fontSize: 12,
    color: colors.textSecondary,
    flexShrink: 0,
  },
  slashShortcuts: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    gap: 8,
    flexShrink: 1,
  },
  slashKbd: {
    fontSize: 11,
    lineHeight: 14,
    color: colors.textSecondary,
  },
  resizeHandle: {
    position: 'absolute',
    top: 6,
    right: 6,
    width: 18,
    height: 18,
    alignItems: 'flex-end',
    justifyContent: 'flex-start',
    zIndex: 2,
  },
  field: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    fontSize: 15,
    lineHeight: 22,
    color: colors.text,
    textAlignVertical: 'top',
    borderWidth: 0,
    backgroundColor: 'transparent',
  },
  footer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingBottom: 8,
    gap: 8,
  },
  footerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  footerIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  footerIconActive: {
    backgroundColor: colors.accentSoft,
  },
  sendBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.accent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendBtnDisabled: {
    opacity: 0.4,
  },
  abortBtn: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 8,
    backgroundColor: '#fef2f2',
  },
  abortText: {
    color: colors.danger,
    fontSize: 13,
    fontWeight: '600',
  },
})
