import { StyleSheet } from 'react-native'
import { colors } from '../theme'

export const uiStyles = StyleSheet.create({
  panelHeader: {
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 10,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  panelHeaderText: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  panelTitle: {
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: -0.15,
    color: colors.text,
  },
  panelSubtitle: {
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '500',
    color: colors.textSecondary,
  },
  panelActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexShrink: 0,
    paddingTop: 2,
  },
  publishBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: colors.accentSoft,
  },
  publishBtnPressed: {
    opacity: 0.85,
  },
  publishBtnText: {
    fontSize: 12,
    fontWeight: '500',
    color: colors.accent,
  },
  secondaryBtn: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: colors.hover,
  },
  secondaryBtnPressed: {
    backgroundColor: colors.borderLight,
  },
  secondaryBtnText: {
    fontSize: 12,
    fontWeight: '500',
    color: colors.textSecondary,
  },
  iconBtn: {
    width: 30,
    height: 30,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.hover,
  },
  iconBtnPressed: {
    backgroundColor: colors.borderLight,
  },
  btnDisabled: {
    opacity: 0.5,
  },
  listItem: {
    marginHorizontal: 20,
    marginBottom: 10,
  },
  fileCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    backgroundColor: colors.surface,
  },
  fileCardSelected: {
    borderColor: colors.accent,
  },
  fileCardPressed: {
    backgroundColor: colors.hover,
  },
  fileCardIcon: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: colors.hover,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    overflow: 'hidden',
  },
  fileCardIconCover: {
    padding: 0,
  },
  fileCardCover: {
    width: 36,
    height: 36,
  },
  fileCardMain: {
    flex: 1,
    minWidth: 0,
  },
  fileCardTitle: {
    fontSize: 14,
    fontWeight: '400',
    color: colors.text,
  },
  fileCardMeta: {
    marginTop: 4,
    fontSize: 12,
    color: colors.textSecondary,
  },
  fileCardDesc: {
    marginTop: 4,
    minHeight: 36,
    fontSize: 12,
    lineHeight: 18,
    color: colors.textSecondary,
  },
  fileCardDescEmpty: {
    opacity: 0,
  },
  actionBarReadonly: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.textSecondary,
    marginRight: 4,
  },
  actionBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    opacity: 0.72,
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 10,
    borderWidth: StyleSheet.hairlineWidth,
    borderTopWidth: 0,
    borderColor: colors.border,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    backgroundColor: '#f4f4f5',
    marginTop: -1,
  },
  actionBarSelected: {
    borderColor: colors.accent,
  },
  actionBarStart: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  actionBarMain: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    flexWrap: 'wrap',
    gap: 6,
  },
  actionIcon: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  actionCount: {
    minWidth: 8,
    fontSize: 12,
    color: colors.textSecondary,
  },
  emptyBody: {
    gap: 8,
    paddingVertical: 36,
    paddingHorizontal: 20,
    alignItems: 'center',
  },
  emptyHint: {
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
    color: colors.textSecondary,
  },
  emptyMeta: {
    fontSize: 12,
    lineHeight: 18,
    textAlign: 'center',
    color: colors.textSecondary,
    opacity: 0.9,
  },
  statGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    paddingHorizontal: 20,
    paddingTop: 10,
  },
  statCard: {
    minWidth: '30%',
    flexGrow: 1,
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: colors.hover,
  },
  statCardActive: {
    backgroundColor: colors.accentSoft,
  },
  statLabel: {
    fontSize: 11,
    color: colors.textSecondary,
  },
  statLabelActive: {
    color: colors.accent,
    fontWeight: '500',
  },
  statValue: {
    marginTop: 4,
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
  },
  statValueActive: {
    color: colors.accent,
  },
  chipRow: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    gap: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  chip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: colors.hover,
  },
  chipActive: {
    backgroundColor: colors.accentSoft,
  },
  chipLabel: {
    fontSize: 12,
    fontWeight: '400',
    color: colors.textSecondary,
  },
  chipLabelActive: {
    color: colors.accent,
    fontWeight: '600',
  },
})
