import { Platform, StyleSheet } from 'react-native'
import { colors } from '../theme'

export const fieldStyles = StyleSheet.create({
  sectionTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
  },
  infoRow: { gap: 4 },
  infoLabel: { fontSize: 12, fontWeight: '500', color: colors.textSecondary },
  infoValue: { fontSize: 14, color: colors.text, lineHeight: 20 },
  mono: {
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    fontSize: 12,
  },
  block: { gap: 6, width: '100%' },
  label: { fontSize: 13, fontWeight: '500', color: colors.text },
  hint: { fontSize: 12, lineHeight: 17, color: colors.textSecondary },
  textareaBox: {
    width: '100%',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 6,
    backgroundColor: colors.bg,
    overflow: 'hidden',
  },
  textareaBoxReadonly: {
    backgroundColor: colors.inputBg,
  },
  textareaInput: {
    width: '100%',
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 14,
    lineHeight: 20,
    color: colors.text,
    backgroundColor: 'transparent',
    ...Platform.select({ web: { outlineWidth: 0 } as object, default: {} }),
  },
  inlineBtn: {
    flexShrink: 0,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 6,
    backgroundColor: colors.bg,
    paddingHorizontal: 12,
    paddingVertical: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  inlineBtnPressed: {
    backgroundColor: colors.hover,
  },
  inlineBtnText: {
    fontSize: 12,
    fontWeight: '500',
    color: colors.textSecondary,
  },
  actionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  choiceList: { gap: 6 },
  choice: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: colors.surface,
  },
  choiceActive: { borderColor: colors.accent, backgroundColor: colors.accentSoft },
  choiceText: { fontSize: 13, color: colors.text },
  choiceTextActive: { color: colors.accent, fontWeight: '600' },
  sliderBlock: {
    gap: 8,
    paddingTop: 4,
    width: '100%',
  },
  sliderHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  sliderValue: {
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    color: colors.textSecondary,
  },
  nativeTrackHit: {
    height: 24,
    justifyContent: 'center',
  },
  nativeTrack: {
    height: 6,
    borderRadius: 999,
    backgroundColor: colors.hover,
    overflow: 'hidden',
  },
  nativeFill: {
    height: 6,
    borderRadius: 999,
    backgroundColor: colors.accent,
  },
  nativeThumb: {
    position: 'absolute',
    top: 5,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: colors.accent,
    borderWidth: 2,
    borderColor: '#fff',
  },
})
