import { StyleSheet } from 'react-native'
import { colors } from '../theme'

export const settingsUiAuthStyles = StyleSheet.create({
  authInput: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 11,
    minHeight: 42,
    backgroundColor: colors.inputBg,
    color: colors.text,
    fontSize: 14,
  },
  authTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.text,
    letterSpacing: 0.2,
  },
  authSubtitle: {
    fontSize: 13,
    lineHeight: 20,
    color: colors.textSecondary,
    marginBottom: 4,
  },
  authCard: {
    backgroundColor: colors.surface,
    borderRadius: 14,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    paddingHorizontal: 16,
    paddingVertical: 16,
    gap: 12,
    width: '100%',
  },
  authForm: {
    gap: 10,
    width: '100%',
  },
  otpRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    width: '100%',
  },
  otpInputGrow: {
    flex: 1,
    minWidth: 0,
  },
  otpSendBtn: {
    minHeight: 42,
    minWidth: 108,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.inputBg,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  otpSendBtnDisabled: {
    opacity: 0.5,
  },
  otpSendBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.text,
  },
  authSubmit: {
    marginTop: 4,
    minHeight: 44,
    borderRadius: 10,
    backgroundColor: colors.accent,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 11,
    paddingHorizontal: 16,
  },
  authSubmitText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: 0.2,
  },
  authFooterRow: {
    marginTop: 4,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  authFooterMuted: {
    fontSize: 13,
    color: colors.textSecondary,
  },
  authFooterLink: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.accent,
  },
  authInlineHint: {
    fontSize: 12,
    lineHeight: 18,
    color: colors.textSecondary,
  },
  socialBlock: {
    width: '100%',
    gap: 4,
    marginTop: 4,
  },
  socialDivider: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 8,
    marginBottom: 6,
  },
  socialDividerLine: {
    flex: 1,
    height: StyleSheet.hairlineWidth,
    backgroundColor: colors.borderLight,
  },
  socialDividerText: {
    fontSize: 12,
    color: colors.textSecondary,
  },
  socialGrid: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
    paddingVertical: 4,
  },
  socialBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.bg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  socialBtnDisabled: {
    opacity: 0.32,
    backgroundColor: colors.inputBg,
  },
})
