name: Sync to Gitee

on:
  push:
    branches:
      - main # 或 master，根据你的默认分支调整

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the GitHub organization repos to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/你的GitHub用户名
          dst: gitee/你的Gitee用户名
          dst_key: ${{ secrets.GITEE_SSH_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: user
          # 仅同步当前仓库
          static_list: "你的仓库名"
          force_update: true
